### PR TITLE
feat: Animate donate heart more lively

### PR DESCRIPTION
**Pull request by oSumAtrIX**
https://github.com/ReVanced/revanced-website/assets/13122796/ef932e10-fa53-44cc-852b-28376bf5b716

### CODE REVIEW

**Comment by PalmDevs** [comment]
Currently, bigger hearts can make the page overflow. To fix this, you'd have to set `overflow-x: hidden` on the parent element of the `main` element. I'm not sure if you're able to do that or not.

**Comment by oSumAtrIX** [comment]
@PalmDevs I am not sure what you mean by overflow, nothing seems out of the ordinary

**Comment by PalmDevs** [comment]
> @PalmDevs I am not sure what you mean by overflow, nothing seems out of the ordinary

Occasionally some big hearts will pop up and go over the screen edge in the animation causing temporary horizontal overflows.

**Comment by oSumAtrIX** [comment]
@PalmDevs Can you record the issue? Maybe this can be solved via overflow hidden

**Review by Ushie — APPROVED** [review]

**Pull request merged**
