### PR TITLE
fix: meta tag indent

### PR DESCRIPTION
**Pull request by PickleNik**
Screenshot 2023-02-04 at 10 11 26 PM

### CODE REVIEW

**Comment by xafn** [comment]
💀

**Comment by oSumAtrIX** [comment]
`refactor: fix invalid padding`

**Comment by xafn** [comment]
mm You're always good with commit names

**Comment by PickleNik** [comment]
> mm You're always good with commit names

I wouldn't call it padding tho, it's an indent

**Comment by oSumAtrIX** [comment]
Ye, just wanted to point out that it's a refactor

**Comment by Axelen123** [comment]
💀

**Pull request merged**
