### PR TITLE
feat(poll): prevent submission, when there is no selection

### LINKED ISSUE #72: fix: prevent poll submission, when there is no selection
## Issue

Currently, you can press the "Submit" button even when there is no selection.

## Solution

Disable the "Submit" button, when there is no selection or round-robin, until at least a selection was made when the end was reached.

### PR DESCRIPTION
**Pull request by Ushie**
Fixes #72

### CODE REVIEW

**Review by oSumAtrIX — APPROVED** [review]
While this PR solves #71, it does not help the user to solve this issue on their end. Basically, the user has to go back and make a selection, and the "flow" breaks. Minor issue but worth consideration regardless in favor of UX.

**Comment by Ushie** [comment]
How should that be resolved? should a button be added to the popup to go back to Page 1?

**Comment by Ushie** [comment]
Or did you mean in terms of text clarity/explanation

**Comment by Ushie** [comment]
Got it, should the "review selection" button always be displayed? or should it only be displayed after they view all the pages for their first time

**Comment by oSumAtrIX** [comment]
At least after the first selection, but making it show up after all logos have been reviewed sounds like a good idea.

**Comment by Ushie** [comment]
Also I'm unsure so I'll ask, "round-robin" would be simply going back to the first page if there has been no selection made? Would you rename the "Next" button to "Go back" or keep it as "Next"? I feel like Next would be better but would that give an implication that the logos will be different?

**Comment by oSumAtrIX** [comment]
Basically:
1. Queue all submissions into a FIFO list and mark the last pushed one as the "last" submission
2. Pop X amount and display them to the user
3. User makes their selection; push the rest of the unselected submissions back to the list
4. When the submission marked as "last" is poped but the user has not selected any submission repeat with `2.` at the moment the user makes a selection (or if they made one before "last" was poped), display the button to review the submission and allow the user to commit it.

**Comment by Ushie** [comment]
Would that not be accomplished easier if we just:

```diff
	function nextPage() {
		if (currentPage >= logoPages || submit) return null;
		currentPage++;

		min = currentPage * logoAmount;
		max = min + logoAmount;

		if (currentPage < logoPages) {
			const nextPage = currentPage + 1;
			const nextMin = nextPage * logoAmount;
			const nextMax = nextMin + logoAmount;
			logos.slice(nextMin, nextMax).forEach(({ variants }) => {
				variants.forEach((variant) => preloadImage(variant.gdrive_direct_url));
			});
		}
+             if (currentPage = finalPage) {
+                 showSubmit = true;
+             }
		transitionDirection = 5;
	}```

**Comment by Ushie** [comment]
Oh I see the point of your message, you want the logos that aren't selected not to show up on the round-robin, hm

**Comment by oSumAtrIX** [comment]
In that case, the user will have to go back to reselect logos they might have been interested in before or when they have not made any selection.

**Comment by Axelen123** [comment]
@Ushie could you make the button unclickable if nothing has been selected?

**Comment by Ushie** [comment]
I'll continue working on this tomorrow after school if things go well 👍

**Comment by Ushie** [comment]
I'll continue working on this tomorrow after school if things go well 👍

**Comment by Ushie** [comment]
TODO:

- [ ] Next round-about
- [ ] Previous round-about after first next round-about
- [ ] Allow review submission after reaching the last page once
- [ ] Option to go back to viewing logos when in review mode

**Review by Axelen123 — CHANGES_REQUESTED** [review]

**Review by Axelen123 — APPROVED** [review]

**Pull request merged**
