### PR TITLE
Slight redesign to better match new logo

### PR DESCRIPTION
**Pull request by PickleNik**
https://github.com/revanced/revanced-website/assets/31113245/4cec6e4f-728f-4add-931d-845dd5fbc499

https://github.com/revanced/revanced-website/assets/31113245/43d304f3-e6db-4d8e-982c-662d6b718493

### CODE REVIEW

**Comment by PickleNik** [comment]
this includes #91 as the 1st commit

**Comment by PickleNik** [comment]
but ironically doesn't have those social icons in the navbar on desktop

**Comment by PickleNik** [comment]
Will resolve conflicts tomorrow

**Comment by Ushie** [comment]
I'm not sure about coloring the download button, we're following M3 Design and the gradient looks weird on it

**Comment by oSumAtrIX** [comment]
The gradients don't look well on the buttons. Have you tried using only two out of the three triadic colors?

**Comment by PickleNik** [comment]
yeah I agree gradients look goofy on the buttons

how's this?
Screenshot 2023-06-06 at 1 02 55 PM

**Comment by PickleNik** [comment]
> Settings modal button should stay in sidebar, it's not of huge significance to take space in the navbar

hmm but then it looks weird with nothing on the right

Screenshot 2023-06-06 at 1 04 45 PM
Screenshot 2023-06-06 at 1 05 21 PM

**Comment by oSumAtrIX** [comment]
May be off topic, but what if the nav bar is at the bottom? It would blend nicely with the animated background

**Comment by oSumAtrIX** [comment]
> yeah I agree gradients look goofy on the buttons
> 
> how's this? 

Definitely an improvement but I am personally still not convinced. Maybe a solid color is actually the best option. Leaving this choice to someone else though

**Comment by PickleNik** [comment]
> May be off topic, but what if the nav bar is at the bottom? It would blend nicely with the animated background and come in favour of reachability

Screenshot 2023-06-06 at 1 08 40 PM

**Comment by oSumAtrIX** [comment]
Since now, there is a lot of space at the top, moving header, the description to the top may fill the empty void. Probably needs more experimenting

**Comment by PickleNik** [comment]
solid color better
Screenshot 2023-06-06 at 1 20 06 PM
Screenshot 2023-06-06 at 1 20 27 PM

**Comment by PickleNik** [comment]
changed it to blue

**Comment by PickleNik** [comment]
https://github.com/revanced/revanced-website/assets/31113245/d52ead25-9d70-401b-9861-ced79bd5d8c1

added deez

**Comment by xafn** [comment]
Woah just seeing this PR now, I'm not sure if I like any of the changes here 😭 We're aiming for a M3 design, and this would violate a lot of its rules. Maybe we could add a theme option, we were thinking of having a pink version of the website at one point.

**Comment by oSumAtrIX** [comment]
image

:trollface:

**Comment by xafn** [comment]
:GUH: my website only uses "M3" colours (coincidence, I just colour picked from the hero image), nothing else about it is M3 like.

**Comment by oSumAtrIX** [comment]
M3 is quite restrictive and maybe too restrictive, which would prevent changes like the one in this PR regarding the navigation bar. Maybe it is worth reconsidering the specification.

**Comment by xafn** [comment]
Well, the navigation bar change isn't really necessary imo, don't think it needs to be floating. If there are concerns about big screens, we could just center it.

**Comment by oSumAtrIX** [comment]
Yeah, the change isn't motivated by necessity. It is just a visual change.

**Comment by xafn** [comment]
Well then, while Nik's PR is good in some aspects, it still violates M3 guidelines. I do understand M3 is pretty restrictive, but I'd want to follow it as closely as possible for visual consistency with Manager. To mitigate future PRs with drastic visual changes, maybe we could add documentation for the website on its design.

**Comment by PickleNik** [comment]
> Woah just seeing this PR now, I'm not sure if I like any of the changes here 😭 We're aiming for a M3 design, and this would violate a lot of its rules. Maybe we could add a theme option, we were thinking of having a pink version of the website at one point.

what is the point of using m3 again?

**Comment by xafn** [comment]
Consistency with Manager, makes it feel very familiar for Android users. Also just what we've been going with this entire time. I don't mind straying away from M3 of course, but having it be a mix of M3 and some random design would be weird.

**Comment by PickleNik** [comment]
> Consistency with Manager, makes it feel very familiar for Android users. Also just what we've been going with this entire time. I don't mind straying away from M3 of course, but having it be a mix of M3 and some random design would be weird.

it doesn't look too weird to me

**Comment by PickleNik** [comment]
the navbar fits in pretty nicely

**Comment by oSumAtrIX** [comment]
@PickleNik We either follow the specifications of M3 or we don't. So far, we have followed the specs, which is why it would be breaking to merge your PR, regardless to me, your change looks better to me than M3's strict specs, I am open for either way

**Comment by xafn** [comment]
> We either follow the specifications of M3 or we don't.
yoppp
I mean yeah I don't really mind the change visually speaking, cuz well, I used that design before, but for the sake of consistency I would rather not have this.

**Comment by oSumAtrIX** [comment]
Contributing guidelines can be added to this repository to avoid future invalid pull requests. In this case, it could mention following the M3 specs.

**Comment by xafn** [comment]
im sorry nikita

**Comment by xafn** [comment]
Ah, @PickleNik note that I made some changes to the footer so make sure you fetch that from dev branch.

**Comment by PickleNik** [comment]
> Ah, @PickleNik note that I made some changes to the footer so make sure you fetch that from dev branch.

the current PR had no conflicts so there should be no issue merging those

**Pull request closed without merging**
