### PR TITLE
feat: add modal icons

### PR DESCRIPTION
**Pull request by PalmDevs**
:trollface:

### CODE REVIEW

**Comment by kazimmt** [comment]
It doesn't match with Material icon/symbol
https://fonts.google.com/icons?icon.query=gear&icon.set=Material+Symbols

**Comment by xafn** [comment]
wait dont you have push access

**Comment by Axelen123** [comment]
> omg merge this already

merge it urself you are in the frontend team lol

**Comment by PalmDevs** [comment]
yall explode

**Comment by Axelen123** [comment]
cope

**Pull request merged**
