### PR TITLE
feat: add skip navigation button

### PR DESCRIPTION
**Pull request by zalnaRs**
Fixes a part of #34 

https://github.com/revanced/revanced-website/assets/53659756/0cc72acf-5ab3-425a-a035-083d19772acc

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Functionality wise looks complete, but the design should match the websites/m3

**Comment by zalnaRs** [comment]
> Functionality wise looks complete, but the design should match the websites/m3

What classes should I use for the link?

**Comment by oSumAtrIX** [comment]
Which link

**Comment by oSumAtrIX** [comment]
@xafn May know which CSS classes to use

**Review by xafn — APPROVED** [review]

**Review by xafn — APPROVED** [review]

**Comment by xafn** [comment]
Thank you for your contribution!

**Pull request merged**
