### PR TITLE
fix: Remove unnecessary app version sorting

### LINKED ISSUE #238: Bug: Patches List - Sorting of YouTube's Compatible Versions (Expanded List)
Hi!.  :wave: 
And Thanks for all of Your (plural) hard work on this Awesome Project, BTW!.  :grin: 

## **issue:** 

  For some reason (that I can't seem to understand right now), when Listing the Patches for the (main) YouTube App on the Website and expanding the List of Compatible Versions, the Recommended (and, incidentally, the Latest Compatible) version of the App gets put in the middle of the List and the whole List is, weirdly, sorted in groups - that I can't understand how exactly they end up Like that / can't understand the Logic/Pattern for that Sorting.
 :thinking: 

I'm currently away from any Computer and just using Chrome on My Android Phone (and I'm in a hurry so I can't Linger on this for Long right now).

Here's a helping (shortcut) Link for the page (You still need to MANUALLY expand the List of Compatible Versions):
  **[ReVanced - Patches for ReVanced (YouTube)](https://revanced.app/patches?pkg=com.google.android.youtube)**    

Sorry that I can't help Debug and explain the reason for this big right now.  :bowing_man: 
  (I usually do...)

Here's in hopes this issue has a very easy Fix.
Cheers!.  :beers: 

  C Ya L8r then!.    :stuck_out_tongue_winking_eye:

### PR DESCRIPTION
**Pull request by Ushie**
I couldn't figure out why these lines of code were here, or if removing them would effect anything, but it seems to work perfectly fine
Closes #238

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
What do you mean? The version is not according to semver specs.

**Comment by KTibow** [comment]
Yes, yet we rely on the `semver` package for sorting the items.

**Comment by KTibow** [comment]
> removed

Are you saying sorting the supported versions should be entirely disabled? Or to replace it instead of entirely removing it?

**Comment by oSumAtrIX** [comment]
I am saying the version should not be parsed as semve

**Comment by KTibow** [comment]
Well, please explicitly state if you mean it should be parsed another way (most likely) or not parsed (literal interpretation of what you're saying)

**Comment by Ushie** [comment]
How else do you propose we sort it?

**Comment by oSumAtrIX** [comment]
As stated in my previous comment, there is no requirement to sort by version name at all.

**Comment by KTibow** [comment]
Are you saying we should use the sorting provided by the backend instead? If so, that sounds like you should make a separate issue for that

**Comment by oSumAtrIX** [comment]
The backend does not specify any sorting and is considered to be random. No issue is necessary

**Comment by KTibow** [comment]
What I'm saying is if you want to remove the current sorting, you should discuss that in a place like an issue first.

**Comment by oSumAtrIX** [comment]
Since it's discussed here with a clear solution, that won't be necessary anymore.

**Pull request merged**
